/**
 * Canonical ChronoPay API error code taxonomy.
 *
 * This module is the single source of truth for every error code that exits
 * the API surface. Codes are organized as a discriminated union that
 * distinguishes:
 *
 * - **PUBLIC** codes (`scope: "public"`): a stable, versioned contract. Safe to
 *   expose to API clients. These never change HTTP status or semantics within
 *   a major version.
 * - **INTERNAL** codes (`scope: "internal"`): operational/diagnostic details
 *   used only in logging and internal handling. They are never exposed on the
 *   public API surface as-is (see `sendError`/`sendInternalError`).
 *
 * Messages are routed through i18n keys (`messageKey`) resolved by
 * `src/i18n/messageLoader.ts` at response time; code is stable contract,
 * message text is not.
 *
 * See `docs/error-codes.md` (regenerated by `npm run generate:error-docs`)
 * for the full documented table.
 */

export type I18nMessageKey = string & { readonly __brand: "I18nMessageKey" };

export function createMessageKey(key: string): I18nMessageKey {
  return key as I18nMessageKey;
}

/**
 * Public error codes: stable, versioned contract exposed to API clients.
 */
export type PublicErrorCode =
  // Validation (400 / 422)
  | "BAD_REQUEST"
  | "VALIDATION_ERROR"
  | "MISSING_REQUIRED_FIELD"
  | "INVALID_PAYLOAD"
  | "MALFORMED_JSON"
  // Authentication (401)
  | "UNAUTHORIZED"
  | "AUTHENTICATION_REQUIRED"
  | "INVALID_TOKEN"
  | "INVALID_API_KEY"
  | "INVALID_SIGNATURE"
  | "INVALID_TIMESTAMP"
  | "TIMESTAMP_OUT_OF_SKEW"
  // Authorization (400 / 403)
  | "FORBIDDEN"
  | "INSUFFICIENT_PERMISSIONS"
  | "INVALID_ROLE"
  // Rate limiting (429)
  | "RATE_LIMITED"
  // Feature flags (503)
  | "FEATURE_DISABLED"
  // Idempotency / replay (400 / 409 / 422)
  | "IDEMPOTENCY_KEY_INVALID"
  | "IDEMPOTENCY_IN_PROGRESS"
  | "IDEMPOTENCY_KEY_MISMATCH"
  | "REPLAY_DETECTED"
  // Content negotiation (406 / 415)
  | "UNSUPPORTED_MEDIA_TYPE"
  | "NOT_ACCEPTABLE"
  // State / lifecycle (404 / 409 / 422)
  | "NOT_FOUND"
  | "CONFLICT"
  | "UNPROCESSABLE_ENTITY"
  // Bundles (422)
  | "BUNDLE_EXPIRED"
  | "BUNDLE_NOT_TRANSFERABLE"
  // Query budget (503)
  | "QUERY_BUDGET_EXCEEDED";

/**
 * Internal error codes: implementation details, never exposed to public API.
 * Used for logging and operational monitoring; `sendInternalError` masks them
 * behind `INTERNAL_ERROR` in production.
 */
export type InternalErrorCode =
  | "DB_ERROR"
  | "INTERNAL_ERROR"
  | "SERVICE_UNAVAILABLE"
  | "CONFIGURATION_ERROR"
  | "FEATURE_FLAG_EVALUATION_ERROR";

/**
 * Union of all known error codes (public + internal).
 */
export type ErrorCode = PublicErrorCode | InternalErrorCode;

/**
 * Taxonomy category used to group codes in documentation and tooling.
 */
export type ErrorCategory =
  | "validation"
  | "authentication"
  | "authorization"
  | "ratelimit"
  | "feature"
  | "idempotency"
  | "content"
  | "state"
  | "bundle"
  | "budget"
  | "infrastructure";

/**
 * Discriminated union for public errors.
 * Each member statically pins `code` to the correct HTTP `status`.
 */
export type PublicError =
  // Validation (400 / 422)
  | {
      readonly scope: "public";
      readonly category: "validation";
      readonly code: "BAD_REQUEST";
      readonly status: 400;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "validation";
      readonly code: "VALIDATION_ERROR";
      readonly status: 422;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "validation";
      readonly code: "MISSING_REQUIRED_FIELD";
      readonly status: 400;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "validation";
      readonly code: "INVALID_PAYLOAD";
      readonly status: 400;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "validation";
      readonly code: "MALFORMED_JSON";
      readonly status: 400;
      readonly messageKey: I18nMessageKey;
    }
  // Authentication (401)
  | {
      readonly scope: "public";
      readonly category: "authentication";
      readonly code: "UNAUTHORIZED";
      readonly status: 401;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "authentication";
      readonly code: "AUTHENTICATION_REQUIRED";
      readonly status: 401;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "authentication";
      readonly code: "INVALID_TOKEN";
      readonly status: 401;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "authentication";
      readonly code: "INVALID_API_KEY";
      readonly status: 401;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "authentication";
      readonly code: "INVALID_SIGNATURE";
      readonly status: 401;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "authentication";
      readonly code: "INVALID_TIMESTAMP";
      readonly status: 401;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "authentication";
      readonly code: "TIMESTAMP_OUT_OF_SKEW";
      readonly status: 401;
      readonly messageKey: I18nMessageKey;
    }
  // Authorization (400 / 403)
  | {
      readonly scope: "public";
      readonly category: "authorization";
      readonly code: "FORBIDDEN";
      readonly status: 403;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "authorization";
      readonly code: "INSUFFICIENT_PERMISSIONS";
      readonly status: 403;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "authorization";
      readonly code: "INVALID_ROLE";
      readonly status: 400;
      readonly messageKey: I18nMessageKey;
    }
  // Rate limiting (429)
  | {
      readonly scope: "public";
      readonly category: "ratelimit";
      readonly code: "RATE_LIMITED";
      readonly status: 429;
      readonly messageKey: I18nMessageKey;
    }
  // Feature flags (503)
  | {
      readonly scope: "public";
      readonly category: "feature";
      readonly code: "FEATURE_DISABLED";
      readonly status: 503;
      readonly messageKey: I18nMessageKey;
    }
  // Idempotency / replay (400 / 409 / 422)
  | {
      readonly scope: "public";
      readonly category: "idempotency";
      readonly code: "IDEMPOTENCY_KEY_INVALID";
      readonly status: 400;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "idempotency";
      readonly code: "IDEMPOTENCY_IN_PROGRESS";
      readonly status: 409;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "idempotency";
      readonly code: "IDEMPOTENCY_KEY_MISMATCH";
      readonly status: 422;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "idempotency";
      readonly code: "REPLAY_DETECTED";
      readonly status: 409;
      readonly messageKey: I18nMessageKey;
    }
  // Content negotiation (406 / 415)
  | {
      readonly scope: "public";
      readonly category: "content";
      readonly code: "UNSUPPORTED_MEDIA_TYPE";
      readonly status: 415;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "content";
      readonly code: "NOT_ACCEPTABLE";
      readonly status: 406;
      readonly messageKey: I18nMessageKey;
    }
  // State / lifecycle (404 / 409 / 422)
  | {
      readonly scope: "public";
      readonly category: "state";
      readonly code: "NOT_FOUND";
      readonly status: 404;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "state";
      readonly code: "CONFLICT";
      readonly status: 409;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "state";
      readonly code: "UNPROCESSABLE_ENTITY";
      readonly status: 422;
      readonly messageKey: I18nMessageKey;
    }
  // Bundles (422)
  | {
      readonly scope: "public";
      readonly category: "bundle";
      readonly code: "BUNDLE_EXPIRED";
      readonly status: 422;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "public";
      readonly category: "bundle";
      readonly code: "BUNDLE_NOT_TRANSFERABLE";
      readonly status: 422;
      readonly messageKey: I18nMessageKey;
    }
  // Query budget (503)
  | {
      readonly scope: "public";
      readonly category: "budget";
      readonly code: "QUERY_BUDGET_EXCEEDED";
      readonly status: 503;
      readonly messageKey: I18nMessageKey;
    };

/**
 * Discriminated union for internal errors.
 * These must never reach the public API surface unmasked.
 */
export type InternalError =
  | {
      readonly scope: "internal";
      readonly category: "infrastructure";
      readonly code: "DB_ERROR";
      readonly status: 500;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "internal";
      readonly category: "infrastructure";
      readonly code: "INTERNAL_ERROR";
      readonly status: 500;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "internal";
      readonly category: "infrastructure";
      readonly code: "SERVICE_UNAVAILABLE";
      readonly status: 503;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "internal";
      readonly category: "infrastructure";
      readonly code: "CONFIGURATION_ERROR";
      readonly status: 503;
      readonly messageKey: I18nMessageKey;
    }
  | {
      readonly scope: "internal";
      readonly category: "infrastructure";
      readonly code: "FEATURE_FLAG_EVALUATION_ERROR";
      readonly status: 500;
      readonly messageKey: I18nMessageKey;
    };

/**
 * Union of all error types (public + internal).
 */
export type ErrorType = PublicError | InternalError;

/**
 * Type guard: is this a public (client-safe) error?
 */
export function isPublicError(error: ErrorType): error is PublicError {
  return error.scope === "public";
}

/**
 * Type guard: is this an internal (backend-only) error?
 */
export function isInternalError(error: ErrorType): error is InternalError {
  return error.scope === "internal";
}

/**
 * Public error codes array (runtime counterpart of `PublicErrorCode`).
 */
export const PUBLIC_ERROR_CODES: readonly PublicErrorCode[] = [
  "BAD_REQUEST",
  "VALIDATION_ERROR",
  "MISSING_REQUIRED_FIELD",
  "INVALID_PAYLOAD",
  "MALFORMED_JSON",
  "UNAUTHORIZED",
  "AUTHENTICATION_REQUIRED",
  "INVALID_TOKEN",
  "INVALID_API_KEY",
  "INVALID_SIGNATURE",
  "INVALID_TIMESTAMP",
  "TIMESTAMP_OUT_OF_SKEW",
  "FORBIDDEN",
  "INSUFFICIENT_PERMISSIONS",
  "INVALID_ROLE",
  "RATE_LIMITED",
  "FEATURE_DISABLED",
  "IDEMPOTENCY_KEY_INVALID",
  "IDEMPOTENCY_IN_PROGRESS",
  "IDEMPOTENCY_KEY_MISMATCH",
  "REPLAY_DETECTED",
  "UNSUPPORTED_MEDIA_TYPE",
  "NOT_ACCEPTABLE",
  "NOT_FOUND",
  "CONFLICT",
  "UNPROCESSABLE_ENTITY",
  "BUNDLE_EXPIRED",
  "BUNDLE_NOT_TRANSFERABLE",
  "QUERY_BUDGET_EXCEEDED",
] as const;

/**
 * Internal error codes array (runtime counterpart of `InternalErrorCode`).
 */
export const INTERNAL_ERROR_CODES: readonly InternalErrorCode[] = [
  "DB_ERROR",
  "INTERNAL_ERROR",
  "SERVICE_UNAVAILABLE",
  "CONFIGURATION_ERROR",
  "FEATURE_FLAG_EVALUATION_ERROR",
] as const;

/**
 * Taxonomy singleton: statically defined error entries with i18n keys.
 * Each entry validates the code → status → messageKey relationship and is the
 * runtime truth used by `sendError`, `AppError`, and the doc generator.
 */
export const ERROR_TAXONOMY: Record<ErrorCode, ErrorType> = {
  // --- Validation (400 / 422) ---
  BAD_REQUEST: {
    scope: "public",
    category: "validation",
    code: "BAD_REQUEST",
    status: 400,
    messageKey: createMessageKey("errors.validation.bad_request"),
  },
  VALIDATION_ERROR: {
    scope: "public",
    category: "validation",
    code: "VALIDATION_ERROR",
    status: 422,
    messageKey: createMessageKey("errors.validation.validation_error"),
  },
  MISSING_REQUIRED_FIELD: {
    scope: "public",
    category: "validation",
    code: "MISSING_REQUIRED_FIELD",
    status: 400,
    messageKey: createMessageKey("errors.validation.missing_required_field"),
  },
  INVALID_PAYLOAD: {
    scope: "public",
    category: "validation",
    code: "INVALID_PAYLOAD",
    status: 400,
    messageKey: createMessageKey("errors.validation.invalid_payload"),
  },
  MALFORMED_JSON: {
    scope: "public",
    category: "validation",
    code: "MALFORMED_JSON",
    status: 400,
    messageKey: createMessageKey("errors.validation.malformed_json"),
  },

  // --- Authentication (401) ---
  UNAUTHORIZED: {
    scope: "public",
    category: "authentication",
    code: "UNAUTHORIZED",
    status: 401,
    messageKey: createMessageKey("errors.auth.unauthorized"),
  },
  AUTHENTICATION_REQUIRED: {
    scope: "public",
    category: "authentication",
    code: "AUTHENTICATION_REQUIRED",
    status: 401,
    messageKey: createMessageKey("errors.auth.authentication_required"),
  },
  INVALID_TOKEN: {
    scope: "public",
    category: "authentication",
    code: "INVALID_TOKEN",
    status: 401,
    messageKey: createMessageKey("errors.auth.invalid_token"),
  },
  INVALID_API_KEY: {
    scope: "public",
    category: "authentication",
    code: "INVALID_API_KEY",
    status: 401,
    messageKey: createMessageKey("errors.auth.invalid_api_key"),
  },
  INVALID_SIGNATURE: {
    scope: "public",
    category: "authentication",
    code: "INVALID_SIGNATURE",
    status: 401,
    messageKey: createMessageKey("errors.auth.invalid_signature"),
  },
  INVALID_TIMESTAMP: {
    scope: "public",
    category: "authentication",
    code: "INVALID_TIMESTAMP",
    status: 401,
    messageKey: createMessageKey("errors.auth.invalid_timestamp"),
  },
  TIMESTAMP_OUT_OF_SKEW: {
    scope: "public",
    category: "authentication",
    code: "TIMESTAMP_OUT_OF_SKEW",
    status: 401,
    messageKey: createMessageKey("errors.auth.timestamp_out_of_skew"),
  },

  // --- Authorization (400 / 403) ---
  FORBIDDEN: {
    scope: "public",
    category: "authorization",
    code: "FORBIDDEN",
    status: 403,
    messageKey: createMessageKey("errors.authz.forbidden"),
  },
  INSUFFICIENT_PERMISSIONS: {
    scope: "public",
    category: "authorization",
    code: "INSUFFICIENT_PERMISSIONS",
    status: 403,
    messageKey: createMessageKey("errors.authz.insufficient_permissions"),
  },
  INVALID_ROLE: {
    scope: "public",
    category: "authorization",
    code: "INVALID_ROLE",
    status: 400,
    messageKey: createMessageKey("errors.authz.invalid_role"),
  },

  // --- Rate limiting (429) ---
  RATE_LIMITED: {
    scope: "public",
    category: "ratelimit",
    code: "RATE_LIMITED",
    status: 429,
    messageKey: createMessageKey("errors.ratelimit.rate_limited"),
  },

  // --- Feature flags (503) ---
  FEATURE_DISABLED: {
    scope: "public",
    category: "feature",
    code: "FEATURE_DISABLED",
    status: 503,
    messageKey: createMessageKey("errors.feature.feature_disabled"),
  },

  // --- Idempotency / replay (400 / 409 / 422) ---
  IDEMPOTENCY_KEY_INVALID: {
    scope: "public",
    category: "idempotency",
    code: "IDEMPOTENCY_KEY_INVALID",
    status: 400,
    messageKey: createMessageKey("errors.idempotency.key_invalid"),
  },
  IDEMPOTENCY_IN_PROGRESS: {
    scope: "public",
    category: "idempotency",
    code: "IDEMPOTENCY_IN_PROGRESS",
    status: 409,
    messageKey: createMessageKey("errors.idempotency.in_progress"),
  },
  IDEMPOTENCY_KEY_MISMATCH: {
    scope: "public",
    category: "idempotency",
    code: "IDEMPOTENCY_KEY_MISMATCH",
    status: 422,
    messageKey: createMessageKey("errors.idempotency.key_mismatch"),
  },
  REPLAY_DETECTED: {
    scope: "public",
    category: "idempotency",
    code: "REPLAY_DETECTED",
    status: 409,
    messageKey: createMessageKey("errors.idempotency.replay_detected"),
  },

  // --- Content negotiation (406 / 415) ---
  UNSUPPORTED_MEDIA_TYPE: {
    scope: "public",
    category: "content",
    code: "UNSUPPORTED_MEDIA_TYPE",
    status: 415,
    messageKey: createMessageKey("errors.content.unsupported_media_type"),
  },
  NOT_ACCEPTABLE: {
    scope: "public",
    category: "content",
    code: "NOT_ACCEPTABLE",
    status: 406,
    messageKey: createMessageKey("errors.content.not_acceptable"),
  },

  // --- State / lifecycle (404 / 409 / 422) ---
  NOT_FOUND: {
    scope: "public",
    category: "state",
    code: "NOT_FOUND",
    status: 404,
    messageKey: createMessageKey("errors.resource.not_found"),
  },
  CONFLICT: {
    scope: "public",
    category: "state",
    code: "CONFLICT",
    status: 409,
    messageKey: createMessageKey("errors.resource.conflict"),
  },
  UNPROCESSABLE_ENTITY: {
    scope: "public",
    category: "state",
    code: "UNPROCESSABLE_ENTITY",
    status: 422,
    messageKey: createMessageKey("errors.resource.unprocessable_entity"),
  },

  // --- Bundles (422) ---
  BUNDLE_EXPIRED: {
    scope: "public",
    category: "bundle",
    code: "BUNDLE_EXPIRED",
    status: 422,
    messageKey: createMessageKey("errors.bundle.expired"),
  },
  BUNDLE_NOT_TRANSFERABLE: {
    scope: "public",
    category: "bundle",
    code: "BUNDLE_NOT_TRANSFERABLE",
    status: 422,
    messageKey: createMessageKey("errors.bundle.not_transferable"),
  },

  // --- Query budget (503) ---
  QUERY_BUDGET_EXCEEDED: {
    scope: "public",
    category: "budget",
    code: "QUERY_BUDGET_EXCEEDED",
    status: 503,
    messageKey: createMessageKey("errors.budget.query_budget_exceeded"),
  },

  // --- Infrastructure (500 / 503) ---
  DB_ERROR: {
    scope: "internal",
    category: "infrastructure",
    code: "DB_ERROR",
    status: 500,
    messageKey: createMessageKey("errors.internal.db_error"),
  },
  INTERNAL_ERROR: {
    scope: "internal",
    category: "infrastructure",
    code: "INTERNAL_ERROR",
    status: 500,
    messageKey: createMessageKey("errors.internal.internal_error"),
  },
  SERVICE_UNAVAILABLE: {
    scope: "internal",
    category: "infrastructure",
    code: "SERVICE_UNAVAILABLE",
    status: 503,
    messageKey: createMessageKey("errors.internal.service_unavailable"),
  },
  CONFIGURATION_ERROR: {
    scope: "internal",
    category: "infrastructure",
    code: "CONFIGURATION_ERROR",
    status: 503,
    messageKey: createMessageKey("errors.internal.configuration_error"),
  },
  FEATURE_FLAG_EVALUATION_ERROR: {
    scope: "internal",
    category: "infrastructure",
    code: "FEATURE_FLAG_EVALUATION_ERROR",
    status: 500,
    messageKey: createMessageKey("errors.internal.feature_flag_evaluation_error"),
  },
} as const;

/**
 * Backward-compatible legacy map: `{ status, code }` per code.
 *
 * This preserves the historical `ERROR_CODES` surface consumed across the
 * codebase so existing call-sites migrate to `ERROR_TAXONOMY` incrementally.
 * The entries are derived from, and can never drift from, the taxonomy.
 */
export const ERROR_CODES: Record<ErrorCode, { code: string; status: number }> = Object.fromEntries(
  (Object.keys(ERROR_TAXONOMY) as ErrorCode[]).map((code) => [
    code,
    { code, status: ERROR_TAXONOMY[code].status },
  ]),
) as Record<ErrorCode, { code: string; status: number }>;

/**
 * Backward-compatible type aliases.
 * `ErrorCodeKey` is the union of every known code name; `ErrorCodeString` is
 * the union of every known code string — both equivalent to `ErrorCode`.
 */
export type ErrorCodeKey = ErrorCode;
export type ErrorCodeString = ErrorCode;
