import { describe, it, expect, beforeEach, jest } from "@jest/globals";
import { BKTree, getEditDistanceCap, getLevenshteinDistance } from "../fuzzy/bkTree.js";
import { SynonymService, SynonymRecord } from "../synonymService.js";
import { MarketplaceSearchService } from "../marketplaceSearchService.js";
import { Slot } from "../../types.js";

// Mock Database Row Type matching actual schema columns
interface DbSlotRow {
  id: number;
  professional_id: string;
  start_time: Date;
  end_time: Date;
  category: string;
  price_cents: number;
  supplier_rating: number;
  status: string;
  created_at: Date;
  tags: string[];
}

/**
 * In-memory Mock Postgres Pool for Tag Search & Synonym Registry unit tests.
 * Correctly evaluates queries generated by both SynonymService and MarketplaceSearchService.
 */
class MockSearchPool {
  public slots: DbSlotRow[] = [];
  public synonyms: SynonymRecord[] = [];
  private nextSynonymId = 1;

  async query(sql: string, params: any[] = []): Promise<{ rows: any[]; rowCount?: number }> {
    // 1. SELECT DISTINCT unnest(tags)
    if (sql.includes("SELECT DISTINCT unnest(tags)")) {
      const allTags = new Set<string>();
      for (const slot of this.slots) {
        if (slot.tags) {
          for (const t of slot.tags) {
            allTags.add(t.toLowerCase().trim());
          }
        }
      }
      return { rows: Array.from(allTags).map((t) => ({ tag: t })) };
    }

    // 3. Synonym Admin CRUD Operations
    if (sql.includes("INSERT INTO search_synonyms")) {
      const word = params[0];
      const syns = params[1];
      const record: SynonymRecord = {
        id: this.nextSynonymId++,
        word,
        synonyms: syns,
      };
      this.synonyms.push(record);
      return { rows: [record], rowCount: 1 };
    }

    if (sql.includes("UPDATE search_synonyms")) {
      const word = params[0];
      const syns = params[1];
      const id = params[2];
      const idx = this.synonyms.findIndex((r) => r.id === id);
      if (idx !== -1) {
        this.synonyms[idx] = { id, word, synonyms: syns };
        return { rows: [this.synonyms[idx]], rowCount: 1 };
      }
      return { rows: [], rowCount: 0 };
    }

    if (sql.includes("DELETE FROM search_synonyms")) {
      const id = params[0];
      const idx = this.synonyms.findIndex((r) => r.id === id);
      if (idx !== -1) {
        this.synonyms.splice(idx, 1);
        return { rows: [], rowCount: 1 };
      }
      return { rows: [], rowCount: 0 };
    }

    // 2. Synonym Registry Table Queries
    if (sql.includes("FROM search_synonyms")) {
      if (sql.includes("WHERE id = $1")) {
        const id = params[0];
        const record = this.synonyms.find((r) => r.id === id);
        return { rows: record ? [record] : [] };
      }
      if (sql.includes("WHERE $1 = ANY(synonyms)")) {
        const tag = params[0].toLowerCase().trim();
        const records = this.synonyms.filter((r) => r.synonyms.includes(tag));
        return { rows: records.map((r) => ({ word: r.word })) };
      }
      return { rows: [...this.synonyms] };
    }

    // 4. Slots Search Queries
    if (sql.includes("SELECT COUNT(*)")) {
      const filtered = this.filterSlots(sql, params);
      return { rows: [{ total: filtered.length.toString() }] };
    }

    if (sql.includes("FROM slots")) {
      let filtered = this.filterSlots(sql, params);
      // Implement simple LIMIT pagination support for search method mock
      const limitMatch = sql.match(/LIMIT \$(\d+)/);
      if (limitMatch) {
        const limitIdx = parseInt(limitMatch[1], 10) - 1;
        const limit = params[limitIdx];
        filtered = filtered.slice(0, limit);
      }
      return {
        rows: filtered.map((s) => ({
          id: s.id,
          professional_id: s.professional_id,
          start_time: s.start_time,
          end_time: s.end_time,
          category: s.category,
          price_cents: s.price_cents,
          supplier_rating: s.supplier_rating,
          status: s.status,
          created_at: s.created_at,
          tags: s.tags,
        })),
      };
    }

    return { rows: [] };
  }

  private filterSlots(sql: string, params: any[]): DbSlotRow[] {
    return this.slots.filter((slot) => {
      // Status filter
      if (sql.includes("status =")) {
        const match = sql.match(/status = \$(\d+)/);
        if (match) {
          const statusParam = params[parseInt(match[1], 10) - 1];
          if (slot.status !== statusParam) return false;
        }
      }

      // GIN overlap GIN tag filter: tags && $n::varchar[]
      const tagsMatch = sql.match(/tags && \$(\d+)::varchar\[\]/);
      if (tagsMatch) {
        const idx = parseInt(tagsMatch[1], 10) - 1;
        const expandedTags: string[] = params[idx];
        const hasOverlap = slot.tags.some((t) =>
          expandedTags.includes(t.toLowerCase().trim())
        );
        if (!hasOverlap) return false;
      }

      return true;
    });
  }
}

describe("Burkhard-Keller (BK) Tree Fuzzy Matching", () => {
  it("should match strings correctly based on Levenshtein edit distance", () => {
    const tree = new BKTree(["plumbing", "cleaning", "haircut", "gardening"]);
    
    // Exact match
    expect(tree.search("plumbing", 0)).toEqual(["plumbing"]);
    // 1 edit distance typo
    expect(tree.search("plumbin", 1)).toEqual(["plumbing"]);
    // Distance too small to match
    expect(tree.search("plumb", 1)).toEqual([]);
    // 2 edit distance matching plumbing
    expect(tree.search("plumbii", 2)).toEqual(["plumbing"]);
  });

  it("should correctly scale edit distance cap with query length", () => {
    // Length <= 2 -> 0 distance cap
    expect(getEditDistanceCap(2)).toBe(0);
    expect(getEditDistanceCap(1)).toBe(0);

    // Length 3-5 -> 1 distance cap
    expect(getEditDistanceCap(3)).toBe(1);
    expect(getEditDistanceCap(5)).toBe(1);

    // Length > 5 -> 2 distance cap
    expect(getEditDistanceCap(6)).toBe(2);
    expect(getEditDistanceCap(10)).toBe(2);
  });

  it("should compute Levenshtein distance correctly", () => {
    expect(getLevenshteinDistance("kitten", "sitting")).toBe(3);
    expect(getLevenshteinDistance("plumbing", "plumbin")).toBe(1);
    expect(getLevenshteinDistance("hair", "haircut")).toBe(3);
    expect(getLevenshteinDistance("test", "test")).toBe(0);
  });

  it("should handle empty or duplicate inputs gracefully", () => {
    const tree = new BKTree();
    // Search empty tree
    expect(tree.search("test", 1)).toEqual([]);

    // Insert empty string
    tree.insert("");
    expect(tree.search("", 1)).toEqual([]);

    // Insert duplicates
    tree.insert("plumbing");
    tree.insert("plumbing");
    expect(tree.search("plumbing", 0)).toEqual(["plumbing"]);
  });
});

describe("Synonym Registry & Cycle-Safe Transitive Expansion", () => {
  let pool: MockSearchPool;
  let service: SynonymService;

  beforeEach(() => {
    pool = new MockSearchPool();
    service = new SynonymService(pool as any);
  });

  it("should perform admin CRUD operations on synonym registry", async () => {
    const created = await service.create("plumbing", ["pipe", "drain"]);
    expect(created.word).toBe("plumbing");
    expect(created.synonyms).toEqual(["pipe", "drain"]);

    const all = await service.getAll();
    expect(all).toHaveLength(1);
    expect(all[0].word).toBe("plumbing");

    const single = await service.getById(created.id);
    expect(single).not.toBeNull();
    expect(single!.word).toBe("plumbing");

    const updated = await service.update(created.id, "plumbing", ["pipe", "sewer"]);
    expect(updated).not.toBeNull();
    expect(updated!.synonyms).toEqual(["pipe", "sewer"]);

    const deleted = await service.delete(created.id);
    expect(deleted).toBe(true);
    
    const allAfterDelete = await service.getAll();
    expect(allAfterDelete).toHaveLength(0);
  });

  it("should expand synonyms bidirectionally and transitively", async () => {
    // plumbing -> pipe -> tube
    await service.create("plumbing", ["pipe"]);
    await service.create("pipe", ["tube"]);

    const expanded = await service.expand(["plumbing"]);
    expect(expanded.sort()).toEqual(["pipe", "plumbing", "tube"].sort());
  });

  it("should be cycle-safe and handle synonym loops without infinite recursion", async () => {
    // A -> B and B -> A cycle
    await service.create("plumbing", ["pipe"]);
    await service.create("pipe", ["plumbing"]);

    const expanded = await service.expand(["plumbing"]);
    expect(expanded.sort()).toEqual(["pipe", "plumbing"].sort());
  });

  it("should handle partial updates in admin CRUD", async () => {
    const created = await service.create("plumbing", ["pipe"]);
    
    // Update word only
    const updatedWord = await service.update(created.id, "plumbing-new", undefined);
    expect(updatedWord!.word).toBe("plumbing-new");
    expect(updatedWord!.synonyms).toEqual(["pipe"]);

    // Update synonyms only
    const updatedSyns = await service.update(created.id, undefined, ["drain"]);
    expect(updatedSyns!.word).toBe("plumbing-new");
    expect(updatedSyns!.synonyms).toEqual(["drain"]);
  });

  it("should cache synonym registry in memory and use cache when TTL is not expired", async () => {
    const querySpy = jest.spyOn(pool, "query");
    
    // First call triggers reload
    await service.expand(["plumbing"]);
    const firstCount = querySpy.mock.calls.length;

    // Second call should hit cache and NOT trigger reload
    await service.expand(["plumbing"]);
    const secondCount = querySpy.mock.calls.length;
    
    expect(secondCount).toBe(firstCount);
    
    querySpy.mockRestore();
  });
});

describe("Marketplace Search with Typo Tolerance and Synonyms", () => {
  let pool: MockSearchPool;
  let searchService: MarketplaceSearchService;

  beforeEach(async () => {
    pool = new MockSearchPool();
    searchService = new MarketplaceSearchService(pool as any);

    // Populate mock slots
    pool.slots = [
      {
        id: 1,
        professional_id: "prof_1",
        start_time: new Date(),
        end_time: new Date(Date.now() + 3600000),
        category: "general",
        price_cents: 5000,
        supplier_rating: 4.5,
        status: "available",
        created_at: new Date(),
        tags: ["plumbing", "drain"],
      },
      {
        id: 2,
        professional_id: "prof_2",
        start_time: new Date(),
        end_time: new Date(Date.now() + 3600000),
        category: "general",
        price_cents: 6000,
        supplier_rating: 4.8,
        status: "available",
        created_at: new Date(),
        tags: ["haircut", "styling"],
      },
      {
        id: 3,
        professional_id: "prof_3",
        start_time: new Date(),
        end_time: new Date(Date.now() + 3600000),
        category: "general",
        price_cents: 7000,
        supplier_rating: 4.0,
        status: "available",
        created_at: new Date(),
        tags: ["gardening"],
      },
    ];

    // Register synonyms
    // plumbing synonym is pipe
    pool.synonyms = [
      {
        id: 1,
        word: "plumbing",
        synonyms: ["pipe"],
      },
    ];
  });

  it("should match slots using fuzzy matching (edit distance cap) and synonym expansion", async () => {
    // Querying with typo "plumbin" should find "plumbing" (edit distance 1, len 7 -> cap 2)
    // and expand to "pipe", matching slot 1
    const result = await searchService.search({
      page: 1,
      limit: 10,
      tags: ["plumbin"],
    } as any);

    expect(result.slots).toHaveLength(1);
    expect(result.slots[0].id).toBe(1);
  });

  it("should fall back to exact match when no fuzzy words are found in the registry/slots", async () => {
    // "gardening" is matched exactly (exact match path fallback)
    const result = await searchService.search({
      page: 1,
      limit: 10,
      tags: ["gardening"],
    } as any);

    expect(result.slots).toHaveLength(1);
    expect(result.slots[0].id).toBe(3);
  });

  it("should perform exact match only for short 2-character queries", async () => {
    // Slot with tags ["pi"]
    pool.slots.push({
      id: 4,
      professional_id: "prof_4",
      start_time: new Date(),
      end_time: new Date(Date.now() + 3600000),
      category: "general",
      price_cents: 5000,
      supplier_rating: 4.0,
      status: "available",
      created_at: new Date(),
      tags: ["pi"],
    });

    // Querying "pi" should match slot 4 exactly, but querying "pa" should NOT fuzzy match to "pi"
    // because edit distance cap is 0 for length 2.
    const resExact = await searchService.search({
      page: 1,
      limit: 10,
      tags: ["pi"],
    } as any);
    expect(resExact.slots).toHaveLength(1);
    expect(resExact.slots[0].id).toBe(4);

    const resFuzzyShort = await searchService.search({
      page: 1,
      limit: 10,
      tags: ["pa"], // distance 1 from "pi", but cap is 0
    } as any);
    expect(resFuzzyShort.slots).toHaveLength(0);
  });

  it("should support all-tokens fuzzy matching when multiple tags are queried", async () => {
    // Querying ["plumbin", "haircu"] should match slots with plumbing or haircut
    const result = await searchService.search({
      page: 1,
      limit: 10,
      tags: ["plumbin", "haircu"],
    } as any);

    expect(result.slots).toHaveLength(2);
    const ids = result.slots.map((s) => s.id).sort();
    expect(ids).toEqual([1, 2]);
  });
});
